name: Deploy Static Site

on:
  push:
    branches:
      - main  # run this workflow when you push to main

jobs:
  lint-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # or any LTS version

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run ESLint
      - name: Run ESLint
        run: npx eslint .  # lint all JS files

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # publish the root folder (contains index.html)
