name: Deploy Static Site

on:
  push:
    branches:
      - main  # run this workflow when you push to main

jobs:
  lint-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # or any LTS version

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 3.5. FIX: Grant execute permission to binaries
      # This resolves the 'sh: 1: eslint: Permission denied' error.
      - name: Set permissions for binaries
        run: chmod +x node_modules/.bin/*

      # 4. Run ESLint (Uses the 'lint' script from package.json)
      - name: Run ESLint
        run: npm run lint

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
